openapi: 3.0.0
info:
  title: 'TransMaster API'
  description: "API for TransMaster\n\nLast updated: 2025-04-16 04:08:24"
  contact:
    name: 'Andrey Voinkov'
    email: voinkov.andrey@yandex.ru
  version: 1.0.0
servers:
  -
    url: 'https://api.transmaster.com'
    description: 'Production server'
  -
    url: 'https://staging.transmaster.com'
    description: 'Staging server'
paths:
  /blocks:
    get:
      tags:
        - Блоки
      summary: 'Получение списка блоков'
      operationId: 431c674022dbdf7a53e94dbe33d3a8aa
      responses:
        '200':
          description: 'Список блоков'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/BlocksResponse'
  '/blocks/show/{code}':
    get:
      tags:
        - Блоки
      summary: 'Получение блока по CODE'
      operationId: 9e3c536b42d2f673ba791240160379f3
      parameters:
        -
          name: block
          in: path
          description: 'Code блока'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Данные блока'
          content:
            application/json:
              schema:
                properties:
                  data: { $ref: '#/components/schemas/BlockItem' }
                type: object
  /categories:
    get:
      tags:
        - Категории
      summary: 'Получение списка категорий'
      operationId: d40bd4448424bd166f2de3fd62064ac7
      responses:
        '200':
          description: 'Список категорий с древовидной структурой'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/CategoriesResponse'
  /news:
    get:
      tags:
        - Новости
      summary: 'Получение списка новостей'
      operationId: 6984575858659740ad63e05c94e0a300
      parameters:
        -
          name: tag
          in: query
          description: 'Фильтрация по ID тега'
          required: false
          schema:
            type: integer
        -
          name: pinned
          in: query
          description: 'Фильтрация по закрепленности'
          required: false
          schema:
            type: boolean
        -
          name: page
          in: query
          description: 'Номер страницы пагинации'
          required: false
          schema:
            type: integer
        -
          name: per_page
          in: query
          description: 'Количество записей на странице'
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 'Список новостей с пагинацией'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsResponse'
  '/news/show/{slug}':
    get:
      tags:
        - Новости
      summary: 'Получение новости по ID'
      operationId: 0341265d014ca21e42ecb7d9e5d4076b
      parameters:
        -
          name: slug
          in: path
          description: 'Slug новости'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Данные новости'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsItem'
  /nomenclatures:
    get:
      tags:
        - Номенклатура
      summary: 'Получение списка номенклатур'
      operationId: 9eb7bf090634cea4ccebff2b3bb7ac55
      parameters:
        -
          name: brand
          in: query
          description: 'Фильтрация по бренду'
          required: false
          schema:
            type: string
        -
          name: manufacturer
          in: query
          description: 'Фильтрация по производителю'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'Список номенклатур'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NomenclatureResponse'
  '/nomenclatures/show/{id}':
    get:
      tags:
        - Номенклатура
      summary: 'Получение номенклатуры по ID'
      operationId: 90067f8775fde2496dd9bd476673ba7f
      parameters:
        -
          name: id
          in: path
          description: 'ID номенклатуры'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Данные номенклатуры'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NomenclatureResponse'
  /nomenclatures/search:
    get:
      tags:
        - Номенклатура
      summary: 'Поиск номенклатур'
      operationId: 0fb7a8b1bef4a77ce778b00427e70947
      parameters:
        -
          name: query
          in: query
          description: 'Поисковый запрос'
          required: true
          schema:
            type: string
        -
          name: page
          in: query
          description: 'Номер страницы'
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 'Результаты поиска'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NomenclatureSearchResponse'
  /pages:
    get:
      tags:
        - Страницы
      summary: 'Получение списка страниц'
      operationId: c60c1a152b98b39222c38655169b6062
      parameters:
        -
          name: type
          in: query
          description: 'Фильтрация по типу страницы'
          required: false
          schema:
            type: string
        -
          name: pinned
          in: query
          description: 'Фильтрация по закрепленности'
          required: false
          schema:
            type: boolean
        -
          name: page
          in: query
          description: 'Номер страницы пагинации'
          required: false
          schema:
            type: integer
        -
          name: per_page
          in: query
          description: 'Количество записей на странице'
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 'Список страниц с пагинацией'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PagesResponse'
  '/pages/show/{slug}':
    get:
      tags:
        - Страницы
      summary: 'Получение страницы по slug'
      operationId: 8d3246a0d6105d3039fe089bc367ac42
      parameters:
        -
          name: slug
          in: path
          description: 'Slug страницы'
          required: true
          schema:
            type: string
      responses:
        '200':
          description: 'Данные страницы'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PageItem'
components:
  schemas:
    Link:
      properties:
        url:
          type: string
          example: vk.com/transmaster
        code:
          type: string
          example: vk
        icon:
          type: string
          example: /storage/icon-vk.svg
          nullable: true
        title:
          type: string
          example: VK
      type: object
    Field:
      properties:
        body:
          type: string
          example: 'ЭТО СПИСОК СОЦ СЕТЕЙ В ФУТЕРЕ'
        code:
          type: string
          example: socials
        file:
          type: string
          nullable: true
        links:
          type: array
          items:
            $ref: '#/components/schemas/Link'
        title:
          type: string
          example: 'Соц. сети'
      type: object
    BlockItem:
      properties:
        id:
          type: integer
        name:
          type: string
          example: Футер
        code:
          type: string
          example: footer
        fields:
          type: array
          items:
            $ref: '#/components/schemas/Field'
        metatags:
          oneOf:
            -
              $ref: '#/components/schemas/MetaTags'
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      type: object
    BlocksResponse:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/BlockItem'
      type: object
    CategoryItem:
      properties:
        id:
          type: integer
        parent_id:
          type: integer
          nullable: true
        name:
          type: string
          example: 'Детали выхлопной системы'
        slug:
          type: string
          example: detali-vyxlopnoi-sistemy
        description:
          type: string
          nullable: true
        attachments:
          properties:
            icon:
              type: string
              nullable: true
          type: object
          nullable: true
        pinned:
          description: 'Закреплено на главной'
          type: boolean
        depth:
          type: integer
          example: 0
        metatags:
          oneOf:
            -
              $ref: '#/components/schemas/MetaTags'
          nullable: true
        children:
          type: array
          items:
            $ref: '#/components/schemas/CategoryItem'
      type: object
    CategoriesResponse:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/CategoryItem'
      type: object
    MetaTags:
      properties:
        title:
          type: string
          nullable: true
        description:
          type: string
          nullable: true
        keywords:
          type: string
          nullable: true
      type: object
    NewsItem:
      properties:
        id:
          type: integer
        title:
          type: string
          example: 'Бу! Испугался?'
        body:
          type: string
          example: 'Бу испугался не бойся Я друг, я тебя не обижу Иди сюда, иди ко мне'
        slug:
          type: string
          example: /news/show/3
        pinned:
          type: boolean
          example: true
        attachments:
          properties:
            files:
              type: array
              items:
                type: string
            images:
              type: array
              items:
                type: string
          type: object
        published_at:
          type: string
          format: date-time
          nullable: true
        metatags:
          oneOf:
            -
              $ref: '#/components/schemas/MetaTags'
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        tags:
          type: array
          items:
            properties:
              id:
                type: integer
              name:
                type: string
                example: Новости
              slug:
                type: string
              metatags:
                oneOf:
                  - { $ref: '#/components/schemas/MetaTags' }
                nullable: true
              created_at:
                type: string
                format: date-time
              updated_at:
                type: string
                format: date-time
            type: object
      type: object
    NewsResponse:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/NewsItem'
        links:
          $ref: '#/components/schemas/PaginationLinks'
        meta:
          $ref: '#/components/schemas/PaginationMeta'
        metatags:
          $ref: '#/components/schemas/MetaTags'
      type: object
    NomenclatureResponse:
      properties:
        id:
          type: integer
        guid:
          type: string
        article:
          type: string
        brand:
          type: string
          nullable: true
        manufacturer:
          type: string
          nullable: true
        code:
          type: string
          nullable: true
        slug:
          type: string
        unit_id:
          type: integer
        name:
          type: string
        description:
          type: string
          nullable: true
        country:
          type: string
          nullable: true
        attachments:
          type: array
          items:
            type: string
          nullable: true
        metatags:
          properties:
            title:
              type: string
              nullable: true
            keywords:
              type: string
              nullable: true
            description:
              type: string
              nullable: true
          type: object
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
          nullable: true
        crosses:
          type: array
          items:
            type: object
      type: object
    NomenclatureSearchResponse:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/NomenclatureResponse'
        links:
          properties:
            first:
              type: string
            last:
              type: string
            prev:
              type: string
              nullable: true
            next:
              type: string
              nullable: true
          type: object
        meta:
          properties:
            current_page:
              type: integer
            from:
              type: integer
            last_page:
              type: integer
            links:
              type: array
              items:
                properties:
                  url: { type: string, nullable: true }
                  label: { type: string }
                  active: { type: boolean }
                type: object
            path:
              type: string
            per_page:
              type: integer
            to:
              type: integer
            total:
              type: integer
          type: object
        metatags:
          properties:
            title:
              type: string
              nullable: true
            description:
              type: string
              nullable: true
            keywords:
              type: string
              nullable: true
          type: object
          nullable: true
        description:
          type: string
          nullable: true
      type: object
    PageItem:
      properties:
        id:
          type: integer
        name:
          type: string
          example: Контакты
        body:
          type: string
          example: '<p>Текст страницы</p>'
        slug:
          type: string
          example: contacts
        type:
          description: 'Тип страницы: information, front, contact, knowledge_base и т.д.'
          type: string
          example: information
        pinned:
          type: boolean
          example: false
        attachments:
          type: array
          items:
            type: string
        fields:
          type: object
          nullable: true
        metatags:
          oneOf:
            -
              $ref: '#/components/schemas/MetaTags'
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
      type: object
    PagesResponse:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/PageItem'
        links:
          $ref: '#/components/schemas/PaginationLinks'
        meta:
          $ref: '#/components/schemas/PaginationMeta'
      type: object
    PaginationLinks:
      properties:
        first:
          type: string
          nullable: true
        last:
          type: string
          nullable: true
        prev:
          type: string
          nullable: true
        next:
          type: string
          nullable: true
      type: object
    PaginationLinkItem:
      properties:
        url:
          type: string
          nullable: true
        label:
          type: string
        active:
          type: boolean
      type: object
    PaginationMeta:
      properties:
        current_page:
          type: integer
        from:
          type: integer
        last_page:
          type: integer
        links:
          type: array
          items:
            $ref: '#/components/schemas/PaginationLinkItem'
        path:
          type: string
        per_page:
          type: integer
        to:
          type: integer
        total:
          type: integer
      type: object
    PaginatedResponse:
      properties:
        data:
          type: array
          items:
            type: object
        links:
          $ref: '#/components/schemas/PaginationLinks'
        meta:
          $ref: '#/components/schemas/PaginationMeta'
      type: object
tags:
  -
    name: Блоки
    description: 'API для работы с блоками сайта'
  -
    name: Категории
    description: 'API для работы с категориями'
  -
    name: Новости
    description: 'API для работы с новостями'
  -
    name: Номенклатура
    description: 'API для работы с номенклатурой'
  -
    name: Страницы
    description: 'API для работы со страницами'
