openapi: 3.0.0
info:
  title: 'TransMaster API'
  description: 'API for TransMaster'
  contact:
    name: 'Andrey Voinkov'
    email: voinkov.andrey@yandex.ru
  version: 1.0.0
servers:
  -
    url: 'https://api.transmaster.com'
    description: 'Production server'
  -
    url: 'https://staging.transmaster.com'
    description: 'Staging server'
paths:
  /news:
    get:
      summary: 'Получение списка новостей'
      operationId: 6984575858659740ad63e05c94e0a300
      parameters:
        -
          name: tag
          in: query
          description: 'Фильтрация по ID тега'
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 'Список новостей'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NewsResponse'
  '/news/show/{id}':
    get:
      summary: 'Получение новости по ID'
      operationId: 932b249e392d2a6da8edef77b542bd63
      parameters:
        -
          name: id
          in: path
          description: 'ID новости'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Данные новости'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NewsResponse'
  /nomenclatures:
    get:
      summary: 'Получение списка номенклатур'
      operationId: 9eb7bf090634cea4ccebff2b3bb7ac55
      parameters:
        -
          name: brand
          in: query
          description: 'Фильтрация по бренду'
          required: false
          schema:
            type: string
        -
          name: manufacturer
          in: query
          description: 'Фильтрация по производителю'
          required: false
          schema:
            type: string
      responses:
        '200':
          description: 'Список номенклатур'
          content:
            application/json:
              schema:
                type: array
                items:
                  $ref: '#/components/schemas/NomenclatureResponse'
  '/nomenclatures/show/{id}':
    get:
      summary: 'Получение номенклатуры по ID'
      operationId: 90067f8775fde2496dd9bd476673ba7f
      parameters:
        -
          name: id
          in: path
          description: 'ID номенклатуры'
          required: true
          schema:
            type: integer
      responses:
        '200':
          description: 'Данные номенклатуры'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NomenclatureResponse'
  /nomenclatures/search:
    get:
      summary: 'Поиск номенклатур'
      operationId: 0fb7a8b1bef4a77ce778b00427e70947
      parameters:
        -
          name: query
          in: query
          description: 'Поисковый запрос'
          required: true
          schema:
            type: string
        -
          name: page
          in: query
          description: 'Номер страницы'
          required: false
          schema:
            type: integer
      responses:
        '200':
          description: 'Результаты поиска'
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/NomenclatureSearchResponse'
components:
  schemas:
    NewsResponse:
      properties:
        id:
          type: integer
        title:
          type: string
        body:
          type: string
        slug:
          type: string
        attachments:
          type: array
          items:
            type: string
        published_at:
          type: string
          format: date-time
          nullable: true
        metatags:
          properties:
            title:
              type: string
              nullable: true
            keywords:
              type: string
              nullable: true
            description:
              type: string
              nullable: true
          type: object
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        tags:
          type: array
          items:
            properties:
              id:
                type: integer
              name:
                type: string
              slug:
                type: string
            type: object
      type: object
    NomenclatureResponse:
      properties:
        id:
          type: integer
        guid:
          type: string
        article:
          type: string
        brand:
          type: string
          nullable: true
        manufacturer:
          type: string
          nullable: true
        code:
          type: string
          nullable: true
        slug:
          type: string
        unit_id:
          type: integer
        name:
          type: string
        description:
          type: string
          nullable: true
        country:
          type: string
          nullable: true
        attachments:
          type: array
          items:
            type: string
          nullable: true
        metatags:
          properties:
            title:
              type: string
              nullable: true
            keywords:
              type: string
              nullable: true
            description:
              type: string
              nullable: true
          type: object
          nullable: true
        created_at:
          type: string
          format: date-time
        updated_at:
          type: string
          format: date-time
        deleted_at:
          type: string
          format: date-time
          nullable: true
        crosses:
          type: array
          items:
            type: object
      type: object
    NomenclatureSearchResponse:
      properties:
        data:
          type: array
          items:
            $ref: '#/components/schemas/NomenclatureResponse'
        links:
          properties:
            first:
              type: string
            last:
              type: string
            prev:
              type: string
              nullable: true
            next:
              type: string
              nullable: true
          type: object
        meta:
          properties:
            current_page:
              type: integer
            from:
              type: integer
            last_page:
              type: integer
            links:
              type: array
              items:
                properties:
                  url: { type: string, nullable: true }
                  label: { type: string }
                  active: { type: boolean }
                type: object
            path:
              type: string
            per_page:
              type: integer
            to:
              type: integer
            total:
              type: integer
          type: object
        metatags:
          properties:
            title:
              type: string
              nullable: true
            description:
              type: string
              nullable: true
            keywords:
              type: string
              nullable: true
          type: object
          nullable: true
        description:
          type: string
          nullable: true
      type: object
